#include "filter.h"
#define NZEROS 3
#define NPOLES 3


static float xv[NZEROS+1], yv[NPOLES+1];
#define GAIN   3.245449475e+07f
float filterloop(float input)
{   
		 xv[0] = xv[1]; xv[1] = xv[2]; xv[2] = xv[3]; 
        xv[3] = input / GAIN;
        yv[0] = yv[1]; yv[1] = yv[2]; yv[2] = yv[3]; 
        yv[3] =   (xv[0] + xv[3]) + 3 * (xv[1] + xv[2])
                     + (  0.9875122361f * yv[0]) + ( -2.9749461327f * yv[1])
                     + (  2.9874336501f * yv[2]);

        return yv[3];
}


/*Generated by:   http://www-users.cs.york.ac.uk/~fisher/mkfilter 
filtertype = Butterworth    passtype = Lowpass   ripple =   order = 3  
samplerate = 1000   corner1 = 50  corner2 = adzero = logmin =     */
#define GAINBtw50hz   (3.450423889e+02f)
float  Butterworth50HzLPF(float input)
{ 
      xv[0] = xv[1]; xv[1] = xv[2]; xv[2] = xv[3]; 
        xv[3] = input / GAINBtw50hz;
        yv[0] = yv[1]; yv[1] = yv[2]; yv[2] = yv[3]; 
        yv[3] =   (xv[0] + xv[3]) + 3 * (xv[1] + xv[2])
                     + (  0.5320753683f * yv[0]) + ( -1.9293556691f * yv[1])
                     + (  2.3740947437f * yv[2]);
        
	return yv[3];
}



/* Digital filter designed by mkfilter/mkshape/gencode   A.J. Fisher
   Command line: /www/usr/fisher/helpers/mkfilter -Bu -Lp -o 2 -a 3.0000000000e-02 0.0000000000e+00 -l */
//#define NZEROS 2   #define NPOLES 2  static float xv[NZEROS+1], yv[NPOLES+1];
#define GAINBtw50Hz   1.278738361e+02f
FiltersTypeDef Filters;
void Butterworth30HzLPF(Bw30HzLPFTypeDef* pLPF)
{
	pLPF->xv[0] = pLPF->xv[1];
	pLPF->xv[1] = pLPF->xv[2]; 
  pLPF->xv[2] = pLPF->input / GAINBtw50Hz;
  pLPF->yv[0] = pLPF->yv[1];
	pLPF->yv[1] = pLPF->yv[2]; 
  pLPF->yv[2] = (pLPF->xv[0] + pLPF->xv[2]) + 2 * pLPF->xv[1]
                     + ( -0.7660066009f * pLPF->yv[0]) + (  1.7347257688f * pLPF->yv[1]);
  pLPF->output = pLPF->yv[2];
}
